server:
  port: 8080
spring:
  application:
    name: "Specifications_producer"
  kafka:
#    enable: true
#    bootstrap-servers: localhost:9092
#    properties:
#      security:
#        protocol: SASL_SSL
#      sasl:
#        mechanism: SCRAM-SHA-512
#        jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin"password="admin-secret";'
#    ssl:
#      protocol: TLSv1.2
#      key-store-type: JKS
#      key-store-location: classpath:cert/server.keystore.jks
#      key-store-password: qwe123
#      trust-store-location: classpath:cert/server.keystore.jks
#      trust-store-password: qwe123
#      key-password: qwe123
#      verify-hostname: false
    topic-names:
      output:
        users-action: kafka_topic_users_new
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    consumer:
      group-id: usersX
      auto-offset-reset: earliest

logging:
  level:
    root: INFO
